import { Container, Container2, ImgBox, MyH1, MyImg, MyP } from './styled';

export function Body() {
  return (
    <>
      <MyH1>Destaques</MyH1>
      <MyP>
        Frete grátis e chinelo de brinde é aqui, aproveite por tempo limitado.{' '}
      </MyP>
      <Container>
        <ImgBox>
          <MyImg
            className="img"
            src="/../public/jordan1.svg"
            alt="j1"
            width="300"
            height="302"
          />
        </ImgBox>
        <ImgBox>
          <MyImg
            className="img"
            src="/../public/j2.svg"
            alt="j1"
            width="300"
            height="302"
          />
        </ImgBox>
        <ImgBox>
          <MyImg
            className="img"
            src="/../public/j3.svg"
            alt="j1"
            width="300"
            height="302"
          />
        </ImgBox>
        <ImgBox>
          <MyImg
            className="img"
            src="/../public/j4.svg"
            alt="j1"
            width="300"
            height="302"
          />
        </ImgBox>
        <br/>
    </Container>
    <Container2>
    <ImgBox>
          <MyImg
            className="img"
            src="/../public/j5.svg"
            alt="j1"
            width="300"
            height="302"
          />
        </ImgBox>
        <ImgBox>
          <MyImg
            className="img"
            src="/../public/j6.svg"
            alt="j1"
            width="300"
            height="302"
          />
        </ImgBox>
        <ImgBox>
          <MyImg
            className="img"
            src="/../public/j7.svg"
            alt="j1"
            width="300"
            height="302"
          />
        </ImgBox>
        <ImgBox>
          <MyImg
            className="img"
            src="/../public/j8.svg"
            alt="j1"
            width="300"
            height="302"
          />
        </ImgBox>
    </Container2>
    </>
  );
}
