import type { NextPage } from 'next'
import Head from 'next/head'
import { Body } from '../components/Body'


import { DescBar } from '../components/DescBar'

import { JordanDesc } from '../components/JordanDesc'
import { Logo } from '../components/Logo'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DescBar/>
      <Logo/>
      <JordanDesc/>
      <Body/>
      
    </div>
  )
}

export default Home
