import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { DescBar } from '../components/DescBar'
import { Logo } from '../components/Logo'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DescBar/>
      <Logo/>
      
    </div>
  )
}

export default Home
